# Generated by Django 3.0.8 on 2020-07-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_ownwer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='ownwer',
            new_name='owner',
        ),
    ]
